### ISSUE TITLE
Update for Swift3

### ISSUE THREAD

**Issue by paulrolfe** [IntrepidPursuits/swift-wisdom#51]
Let's add to-do's here that we want to address in the swift 3 transition:
- [ ] Update any changed syntax (obvious)
- [ ] Should we use `ip_` prefix anymore?

**Comment by alexpersian** [comment]
Was there a change in Swift 3 that fixes the need for the `ip_` prefix?

**Comment by paulrolfe** [comment]
No, you never needed it for swift since everything is namespaced. We just never took advantage and I'm wondering if we should now.

EDIT: To clarify, it's just not needed on our own public functions, classes, structs, etc. Extensions should still use it.

**Comment by alexpersian** [comment]
The extension ambiguous naming was what I was concerned about. How do other, larger projects solve this issue?
EDIT: After looking through the repo it seems like it's already limiting the `ip_` prefix to extensions. There was only one instance I found in `PercentAnimate.swift` where `pa_percentAnimate` could be renamed to `ip_percentAnimate`.

**Comment by brightredchilli** [comment]
OK - looks like our decision here is, use ip_ for extensions(this makes me extremely sad), but make sure that we do not prefix with ip for the rest of our code. Thanks for bringing up the awesome discussion.

**Comment by brightredchilli** [comment]
Closing this guy since we have other issues to track swift 3 migration
