### ISSUE TITLE
UIKit

### ISSUE THREAD

**Issue by alexpersian** [IntrepidPursuits/swift-wisdom#59]
Migrate the `UIKit` module to Swift 3.

**Comment by tzm41** [comment]
I could help out~

**Comment by Benuuu** [comment]
@tzm41 each person assigned to one of these tasks (#59, #60, #61, #62, #63) is in charge of delegating and making sure the task is done.  If you're interested in helping out in a specific module  communicate with the person assigned.

**Comment by tzm41** [comment]
@Benuuu Thanks! Already talked to @aspitz-intrepid
