### ISSUE TITLE
Assorted Modules

### ISSUE THREAD

**Issue by alexpersian** [IntrepidPursuits/swift-wisdom#63]
Migrate the following modules to Swift 3:
- Common Types
- Colors
- Sounds
- Timeout
- Version
- Geometry
- Rx

**Comment by Benuuu** [comment]
Rx update is up here: https://github.com/IntrepidPursuits/swift-wisdom/pull/57

**Comment by weberbry** [comment]
No warnings or test for Geometry

**Comment by weberbry** [comment]
No warnings and passings tests for Version

**Comment by mayasaxena** [comment]
No warnings or tests for Common Types

**Comment by weberbry** [comment]
No warnings or tests for Timeout

**Comment by mayasaxena** [comment]
No warnings for Colors, tests will pass when range function in `String+NSRange.swift` is fixed

**Comment by weberbry** [comment]
No warnings or tests for sounds
